title: Sidharth Baveja
author:
  name: Sidharth Baveja
  email: sidharthbav@gmail.com
footer_description: > # this means to ignore newlines until "show_excerpts:"
  Senior Electrical Engineering student at the University of Waterloo. I'm interested
  in Cryptocurrencies, Electric and Autonmous Vehicles, AI, Investing and Personal Development.

#description: > # this means to ignore newlines until "show_excerpts:"
  #Student, Crypto, AI, & Personal Development.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: sidbav
    github:  sidbav
    linkedin: sidharth-baveja
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

gems:
  - jekyll-paginate

paginate: 10
paginate_path: posts/page:num/
google_analytics: G-EQZRSLN033
